---
title: "Occurrence indicators: downscaling"
author:
- Damiano Oldoni
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
---

This document describes how to apply downscaling method on GBIF occurrence data of Invasive Alien Species.

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Install `trias` package:

```{r install_packages}
devtools::install_github("trias-project/trias")
```


Load libraries:

```{r load_libraries}
# Tidyverse packages
library(tidyr)
library(dplyr)
library(magrittr)
library(stringr)
library(readr)
# GBIF related packages
library(rgbif)
# project package
library(trias)
#other pckages
library(lazyeval)
```

# Get data

We can import test data based on a previous download related to taxa in `../data/input/species_test_invasion_curve.tsv`:

```{r load_occ_data}
if (!file.exists("../data/interim/occurrence_species_test_invasion_curve.txt")) {
  gbif_download_key <- "0020843-180131172636756"
  occ <- occ_download_get(key = gbif_download_key, 
                        overwrite = T, 
                        path = "../data/interim/")
  fn <- "occurrence.txt"
  unzip(zipfile = occ, files = fn, 
      exdir = "../data/interim")
  file.rename(from = "../data/interim/occurrence.txt", 
              to = "../data/interim/occurrence_species_test_invasion_curve.txt")
}

occ_df <- read_delim(
  file = "../data/interim/occurrence_species_test_invasion_curve.txt", "\t",
  escape_double = FALSE, trim_ws = TRUE)
```

# Downscaling

New functions should be written in `trias` official project package.
