---
title: "Get occurrences for list of species"
author:
- Peter Desmet
- Damiano Oldoni
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    theme: yeti
    df_print: paged
knit: (function(input_file, encoding) { rmarkdown::render(input_file, encoding = encoding, output_file = paste0("../docs/",sub(".Rmd", ".html", basename(input_file))))})
---

This document describes how to retrieve occurrences for a list of species.

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Install packages:

```{r install_packages}
devtools::install_github("trias-project/trias")
devtools::install_github("ropensci/rgbif")
```

Load libraries:

```{r load_libraries}
# Tidyverse packages
library(dplyr)
library(magrittr)
library(readr)

# Other packages
library(rgbif)
library(trias)
```

Set file paths:

```{r set_file_paths}
# All downloads we've triggered are added to this file:
downloads_output_file <- "data/output/gbif_downloads.tsv"
```

# Download GBIF occurrences

## For species of EU concern

```{r}
input_checklist <- "../data/input/eu_concern_species.tsv"
eu_concern_species <- 
  read_delim(file = input_checklist, 
             "\t", escape_double = FALSE, 
             col_types = cols(
               entry_into_force = col_date(
                 format = "%Y-%m-%d")), 
             trim_ws = TRUE)
taxonKeys <- eu_concern_species["backbone_taxonKey"]
countries <- list(country = c("IT"))
gbif_download_key <- rgbif::occ_download(
  paste("taxonKey = ", paste(taxonKeys$backbone_taxonKey, 
                             collapse = ",")), 
  paste("country = ", paste(countries$country, collapse = ",")), 
  curlopts = list(verbose = TRUE))
```

Check status of download:

```{r}
metadata <- occ_download_meta(key = gbif_download_key)
metadata$key
metadata$status
```

Write download to list of downloads and check pending downloads

```{r}
trias::update_download_list(file = "../data/output/gbif_downloads.tsv", 
                            download_to_add = gbif_download_key, 
                            input_checklist = input_checklist, 
                            countries = countries)
```
